### ISSUE TITLE
Support writing ticks and climbs to Aurora

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/BoardLib#20]
`PUT /v1/ascents/`

Data fields:

```json
["uuid", "climb_uuid", "angle", "is_mirror", "user_id", "attempt_id", "bid_count", "quality", "difficulty", "is_benchmark", "comment", "climbed_at"]
```

`PUT /v2/climbs/`
```json
"uuid", "layout_id", "setter_id", "name", "description", "is_draft", "frames_count", "frames_pace", "frames"
```

Need to determine how UUIDs for both ascents and climbs are generated.

**Comment by wetmore** [comment]
I believe the UUIDs are just UUID v4 without the hyphens. From looking at a few of them, they are 32 character hex digits and the 13th digit is 4.

**Comment by lemeryfertitta** [comment]
> I believe the UUIDs are just UUID v4 without the hyphens. From looking at a few of them, they are 32 character hex digits and the 13th digit is 4.

Thanks! I came to the same conclusion. I have a work in progress PR for this, was able to get these working locally but went on a trip and haven't gone back to finish this up. I'll aim to release something soon.
