### ISSUE TITLE
Incorrect logbook "tries" for Aurora boards with attempts > 10

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/BoardLib#22]
attempt_id actually maps to the attempts table, and although id 1-10 maps directly to number of attempts, the meaning changes for 11 and above.

The sync command could be augmented to return the `attempts` table and then the `logbook_entries` function can be updated to map the `attempt_id` to the real attempt meaning.

Split from https://github.com/lemeryfertitta/BoardLib/issues/21#issuecomment-1945254875

**Comment by lekanteto** [comment]
The app sends the following payload when saving an ascend. So it looks like the attempt_id is not used but only the bid_count.

{
    "angle": 40,
    "attempt_id": 0,
    "bid_count": 12,
    "climb_uuid": "",
    "climbed_at": "",
    "comment": "",
    "difficulty": 14,
    "is_benchmark": false,
    "is_mirror": false,
    "quality": 3,
    "user_id": ,
    "uuid": ""
}

**Comment by lemeryfertitta** [comment]
> it looks like the attempt_id is not used but only the bid_count.

Interesting. I do have ticks that use attempt_id, I wonder if they switched the behavior at some point and have some logic for supporting both.

**Comment by lemeryfertitta** [comment]
While this bug is still technically present, I am closing this one as not worth fixing considering the fact that new logbook entries use bids and that the bug only exists for old logbook entries with >10 attempts.
