### ISSUE TITLE
grade conversion: strange mapping

### ISSUE THREAD

**Issue by lekanteto** [lemeryfertitta/BoardLib#23]
The maping looks strange for higher grades:

    "7C": "V9",
    "7C+": "V10",
    "8A": "V9",
    "8A+": "V10",
    "8B": "V11",
    "8B+": "V12",
    "8C": "V13",
    "8C+": "V14",
    "9A": "V15",

**Comment by lemeryfertitta** [comment]
@lekanteto thanks! You're right, that looks off to me. Starting at `8A` font, the hueco grade needs to be 2 higher. I'll take care of it when I get around to the next release, or you're welcome to submit a PR to adjust this.

**Comment by lemeryfertitta** [comment]
Released in 0.5.0
