### ISSUE TITLE
BoardLib fails with ssl exception on my Windows pc

### ISSUE THREAD

**Issue by lekanteto** [lemeryfertitta/BoardLib#28]
When I run BoardLib on my Windows machine I get the following error:
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)`

Possible solutions are explained here:
[https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests](https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests)

For me this helped:
`pip install python-certifi-win32`

Suggestion:
Provide some information about this in the project's readme or have a FAQ page or something like that.

**Comment by lemeryfertitta** [comment]
Thanks for the report. For now I'll close this issue and it will be searchable by others if it happens to them. From my reading of that answer and some other related pages, it seems like this would be specific to your Python installation and would not be the default for all Windows users, so I think a README update would be a bit premature. If others report the same issue, we can reevaluate.
