### ISSUE TITLE
What hardware do I need to run this program

### ISSUE THREAD

**Issue by climber321** [lemeryfertitta/BoardLib#34]
What hardware would I need to purchase and setup in order for climbdex to light my 8x12OG Kilterboard?  

I have no experience with computers other than basic user skills. And no experience with addressable LEDs. I found a link to climbdex on reddit. 

From watching youtube videos I have gathered I could possibly purchase an esp32 board kit, flash WLED to the board from WLED website, and  hookup ws2811 (312lights x 2) string lights with 10-12 inch spacing, and 5v power booster.  All readily available online.  Am I way off watching these videos?

I would be happy to make a contribution if I can get climbdex working with my kilter board!

**Comment by lemeryfertitta** [comment]
Interesting question! I'd imagine you can purchase an LED kit directly from Kilter. As long as you are using the same LED controller that Kilter provides with their LED kit, Climbdex should be able to communicate with the controller to light up climbs. If you wanted to use a different controller, I suspect their would be some work to implement a new bluetooth communication protocol, but you are certainly welcome to contribute this if you're motivated.

Just a heads-up that the Bluetooth feature is a bit of a work-in-progress. It generally works, but the official Kilter mobile app is probably still a little bit more robust. I'm interested in improving this as well and I would be happy to accept contributions in this area.

**Comment by lemeryfertitta** [comment]
Also, this issue would belong in https://github.com/lemeryfertitta/Climbdex/issues as the Bluetooth support is in Climbdex, not BoardLib. Feel free to open a new issue to continue the discussion there if you have further questions or ideas.
