### ISSUE TITLE
Discrepancy in # of Tries Between Exported Logbook and App View

### ISSUE THREAD

**Issue by PTschaikner** [lemeryfertitta/BoardLib#36]
Firstly, thank you for this wonderful repo—it has potentially solved many of my problems! I started using the "climbing tracker" app to record my climbs because it allows data export, which is not possible with the native Aurora apps, but it would be great to being able to somehow use the aurora data, especially because the visualisations could be made available to many more users. Additionally, I have a DIY tension board with a DIY LED system, and the database download feature might allow me to sync the tension board boulders from the app, which would be awesome.

I have encountered an issue with the exported logbook data. When I export the logbook, the number of tries recorded differs from what is displayed in the app's logbook view. Specifically, I am referring to the "x attempts in y sessions" information (see the screenshot below).

Is there an easy way to extract the data they use to build this "x attempts in y sessions" information? This data could be useful for many users because it gives a much better idea about how much work you put into a project.

I am happy to contribute myself, though I am a beginner and would appreciate some pointers. Any assistance or direction would help me get started and contribute meaningfully.

Thank you!

![signal-2024-06-05-155445](https://github.com/lemeryfertitta/BoardLib/assets/29307376/da7f3a93-b39e-4519-8d2c-acc8d2a8cf87)

**Comment by PTschaikner** [comment]
this is probably tightly related to #22 - I think in the old app they mainly used the attempts_id and mapped it to the table and later they seem to have switched behaviour. I am also using the Log Quig Attempt feature, which might cause additional problems - I will investigate further.

**Comment by PTschaikner** [comment]
Made some progress in understanding the issue:
* before the 2022 update only ascents where recorded with an ascent ID and a lookup table ("old" attempts are marked as "tries" in the tension board app).
* After the update they added the bids table which includes tries that didn't lead to a top.
* Combining the bids and ascents table would allow to create a logbook that contains all information.

I don't know whether you are interested in this functionality, and if my proposed pullrequest (#37) interferes with functionality of your climbdex package. I will keep working on it to get a more complete Logbook.

All the best, and thanks again!

**Comment by lemeryfertitta** [comment]
Definitely interested in that functionality! If you are interested in contributing it I would be happy to review. Thanks for investigating, and thank you for your other PR.

**Comment by gardaholm** [comment]
Danke @PTschaikner such a great addition 🙏
I hope this will finally help us with this issue here https://github.com/lemeryfertitta/Climbdex/issues/55
and we can display attempted boulders for the tensionboard!

**Comment by lemeryfertitta** [comment]
Released in 0.7.0
