### ISSUE TITLE
How can I download the kilter board image for a given climb?

### ISSUE THREAD

**Issue by gabriead** [lemeryfertitta/BoardLib#45]
Hi community,
I don't quite understand how to use the 'download_image' correctly. If I forward board_name ="kilter" and image_filename ="'product_sizes_layouts_sets/36-1.png'" I am only getting board layouts without any highlighted holds. How can I obtain the full image I would also see in my Kilter App?

**Comment by lemeryfertitta** [comment]
@gabriead what is your goal? If your goal is to mimic the behavior of the official apps, you could investigate [the implementation](https://github.com/lemeryfertitta/Climbdex) for [Climbdex](https://climbdex.com/results?minGrade=10&maxGrade=33&name=&angle=any&minAscents=1&sortBy=ascents&sortOrder=desc&minRating=1.0&onlyClassics=0&gradeAccuracy=1&settername=&setternameSuggestion=&holds=&mirroredHolds=&board=kilter&layout=1&size=10&set=1&set=20&roleMatch=strict).

**Comment by gabriead** [comment]
Hi @lemeryfertitta thank you for the fast reply! My goal is to create heatmaps for any given angle and grade that visualize which holds are the most common ones in order to adapt the training. I would like to use YOLO to do that therefore I need the image with the highlighted holds etc. We can also colloborate if you are interested. But I would need the images to train a YOLO classifier for that.

**Comment by gabriead** [comment]
Long story short: could you add a method where one can retrieve the full image for a board/angle/grade?

**Comment by lemeryfertitta** [comment]
> My goal is to create heatmaps for any given angle and grade that visualize which holds are the most common ones in order to adapt the training.

To determine the most common holds for a given grade and angle, you can just look directly at the data in the database and skip the image recognition work entirely. I'd imagine this will be more efficient, more accurate, and easier to implement.

The `frames` column of the `climbs` table will get you a list of all of the holds in a given problem, which can be joined with angle, grade, and ascent count data from `climb_stats` table. This will allow you to build a list of hold popularity for given angles and grades. If you want to visualize that list and need spacial positions, that data is also available (i.e. mapping a given frame to an x-y coordinate on the board). I'd recommend reading through the Climbdex code and exploring the sqlite databases to understand how this is all put together.

**Comment by gabriead** [comment]
Thank you for your suggestions. That gives me the following data:
('AC9FCF7F01FC44BD835CFC41CB2224DA', 'You Don’t Know Me', 'p1096r15p1113r15p1131r15p1149r12p1166r15p1200r13p1234r15p1236r13p1253r15p1270r13p1306r13p1340r13p1358r13p1392r14', 'JustinKo', '2019-02-18 22:45:35.747718', 40, 15.9941, 43152, 2.94017) 
So I assume the string starting with "p1096r15..." are the holds each hold delimited by 'p'? 
Can you give me a hint on how to retrieve the spacial coordinates for each hold from which table?

**Comment by lemeryfertitta** [comment]
Correct, p indicates a placement and r indicates a role. See https://github.com/lemeryfertitta/Climbdex/blob/main/climbdex/db.py#L50-L64 for an example query mapping placementId to x-y coordinate.
