### ISSUE TITLE
Add benchmark info to logbook export

### ISSUE THREAD

**Issue by gardaholm** [lemeryfertitta/BoardLib#48]
I would suggest adding a benchmark column (is_benchmark) to the logbook export. 
This information would be really handy in the export. 

I'm using boardlib right now to display a dynamic grafana dashboard with logbook stats. and this query would make things a lot easier.

---
see PR https://github.com/lemeryfertitta/BoardLib/pull/49

**Comment by lemeryfertitta** [comment]
Merged and released in 0.9.0. Thanks!
